# Generated by Django 2.2.7 on 2020-03-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_gamenews_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameNews',
        ),
    ]
