# Generated by Django 2.2.7 on 2020-03-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_gamenews_gamesinglenews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('strenght', models.IntegerField()),
                ('power', models.IntegerField()),
                ('wepon', models.IntegerField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
