# Generated by Django 2.2.7 on 2020-03-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hero_image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
