# Generated by Django 2.2.7 on 2020-03-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_character_hero_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
    ]
