# Generated by Django 2.2.7 on 2020-03-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_remove_character_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='gamenews',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='gamesinglenews',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
