# Generated by Django 2.2.7 on 2020-03-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20200321_0134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameSingleNews',
        ),
    ]
