# Generated by Django 2.2.7 on 2020-03-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_character_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
    ]
