# Generated by Django 2.2.7 on 2020-03-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_character_gamesinglenews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
    ]
