# Generated by Django 2.2.7 on 2020-03-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote',
            new_name='vote_power',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_strenght',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_weapon',
            field=models.IntegerField(default=0),
        ),
    ]
