# Generated by Django 2.2.7 on 2020-03-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_auto_20200321_1928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
