# Generated by Django 2.2.7 on 2020-03-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
