# Generated by Django 2.2.7 on 2020-03-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0031_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
