# Generated by Django 2.2.7 on 2020-03-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0036_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
