# Generated by Django 2.2.7 on 2020-03-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0040_auto_20200324_0152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameSingleNews',
        ),
    ]
