# Generated by Django 2.2.7 on 2020-03-24 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0042_auto_20200324_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='index.Character'),
        ),
    ]
