# Generated by Django 2.2.7 on 2020-03-24 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0043_auto_20200324_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Character'),
        ),
    ]
