# Generated by Django 2.2.7 on 2020-03-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0044_auto_20200324_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='comment_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.CharacterComment'),
        ),
    ]
