# Generated by Django 2.2.7 on 2020-03-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0045_character_comment_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='comment_set',
        ),
    ]
