# Generated by Django 2.2.7 on 2020-03-24 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0046_remove_character_comment_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
