# Generated by Django 2.2.7 on 2020-03-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0047_character_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='likes',
        ),
    ]
