# Generated by Django 2.2.7 on 2020-03-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0049_character_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
