# Generated by Django 2.2.7 on 2020-03-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0050_character_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
