# Generated by Django 2.2.7 on 2020-03-25 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0053_article_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='user_reaction',
            field=models.ManyToManyField(blank=True, related_name='react', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='character',
            name='likes',
        ),
        migrations.AddField(
            model_name='character',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
