# Generated by Django 2.2.7 on 2020-03-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0054_auto_20200325_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='character',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='character',
            name='user_reaction',
        ),
    ]
