# Generated by Django 2.2.7 on 2020-03-25 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0055_auto_20200325_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
