# Generated by Django 2.2.7 on 2020-03-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0060_viewtrack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewTrack',
        ),
    ]
