# Generated by Django 2.2.7 on 2020-03-26 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0061_delete_viewtrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='Views',
            field=models.ManyToManyField(blank=True, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
    ]
