# Generated by Django 2.2.7 on 2020-03-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0062_character_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='Views',
        ),
        migrations.AddField(
            model_name='character',
            name='Views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
