# Generated by Django 2.2.7 on 2020-03-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0063_auto_20200327_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='Views',
            field=models.IntegerField(default=0),
        ),
    ]
