# Generated by Django 2.2.7 on 2020-03-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0065_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
