# Generated by Django 2.2.7 on 2020-03-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0068_auto_20200327_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(),
        ),
    ]
