# Generated by Django 2.2.7 on 2020-03-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0069_auto_20200327_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
