# Generated by Django 2.2.7 on 2020-03-28 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0072_auto_20200327_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenews',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
