# Generated by Django 2.2.7 on 2020-03-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0074_author_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='cover_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
