# Generated by Django 2.2.7 on 2020-03-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0079_auto_20200329_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
