# Generated by Django 2.2.7 on 2020-03-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0080_auto_20200329_0004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
